In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4914, 6384, 6885, 9304],
 [4914, 6384, 6885, 2164],
 [4914, 1791, 6885, 988],
 [1965, 1073, 721, 8736, 3026],
 [1965, 1073, 721, 8736, 4329],
 [9017, 4914, 8600, 6885, 8908],
 [5770, 9563, 5819, 8736]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4914 6384 6885 9304]
 [   0    0    0    0 4914 6384 6885 2164]
 [   0    0    0    0 4914 1791 6885  988]
 [   0    0    0 1965 1073  721 8736 3026]
 [   0    0    0 1965 1073  721 8736 4329]
 [   0    0    0 9017 4914 8600 6885 8908]
 [   0    0    0    0 5770 9563 5819 8736]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 277ms/step


array([[[-0.04782064,  0.03277239, -0.00863718, -0.01591678,
         -0.03047373,  0.00609707,  0.03503818,  0.03937707,
          0.01853907, -0.04674802],
        [-0.04782064,  0.03277239, -0.00863718, -0.01591678,
         -0.03047373,  0.00609707,  0.03503818,  0.03937707,
          0.01853907, -0.04674802],
        [-0.04782064,  0.03277239, -0.00863718, -0.01591678,
         -0.03047373,  0.00609707,  0.03503818,  0.03937707,
          0.01853907, -0.04674802],
        [-0.04782064,  0.03277239, -0.00863718, -0.01591678,
         -0.03047373,  0.00609707,  0.03503818,  0.03937707,
          0.01853907, -0.04674802],
        [-0.03402727,  0.01030226,  0.02759211,  0.0095404 ,
          0.03740306,  0.020628  , -0.02748964,  0.00294598,
         -0.00119963, -0.04289388],
        [-0.02820742,  0.00721704,  0.0365454 , -0.01010932,
         -0.00635294, -0.03729819,  0.00577191,  0.04509295,
          0.03283745, -0.04015081],
        [-0.03901085,  0.04990535,  0.01976577, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4914, 6384, 6885, 9304])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 49ms/step


array([[-0.04782064,  0.03277239, -0.00863718, -0.01591678, -0.03047373,
         0.00609707,  0.03503818,  0.03937707,  0.01853907, -0.04674802],
       [-0.04782064,  0.03277239, -0.00863718, -0.01591678, -0.03047373,
         0.00609707,  0.03503818,  0.03937707,  0.01853907, -0.04674802],
       [-0.04782064,  0.03277239, -0.00863718, -0.01591678, -0.03047373,
         0.00609707,  0.03503818,  0.03937707,  0.01853907, -0.04674802],
       [-0.04782064,  0.03277239, -0.00863718, -0.01591678, -0.03047373,
         0.00609707,  0.03503818,  0.03937707,  0.01853907, -0.04674802],
       [-0.03402727,  0.01030226,  0.02759211,  0.0095404 ,  0.03740306,
         0.020628  , -0.02748964,  0.00294598, -0.00119963, -0.04289388],
       [-0.02820742,  0.00721704,  0.0365454 , -0.01010932, -0.00635294,
        -0.03729819,  0.00577191,  0.04509295,  0.03283745, -0.04015081],
       [-0.03901085,  0.04990535,  0.01976577, -0.04720313, -0.04998069,
        -0.00753616,  0.04623021,  0.02437515